"""add_email_collum

Revision ID: 16099fff7a3e
Revises: bf72fd423e4e
Create Date: 2026-05-06 22:42:14.269255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16099fff7a3e'
down_revision: Union[str, Sequence[str], None] = 'bf72fd423e4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Добавляем колонку как nullable
    op.add_column('user', sa.Column('email', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=False)
    
    # Заполняем существующие записи временными значениями
    op.execute("""
        UPDATE "user" 
        SET email = CONCAT('temp_', id, '@placeholder.com') 
        WHERE email IS NULL
    """)
    
    # Делаем колонку NOT NULL
    op.alter_column('user', 'email', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_column('user', 'email')
    # ### end Alembic commands ###
