"""add_description_collum

Revision ID: 5cc4642f41d5
Revises: 16099fff7a3e
Create Date: 2026-05-19 21:01:38.400095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cc4642f41d5'
down_revision: Union[str, Sequence[str], None] = '16099fff7a3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dictionary', sa.Column('description', sa.String(length=90), nullable=True))
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=False)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_column('dictionary', 'description')
    # ### end Alembic commands ###
