"""fix_relationships

Revision ID: bc5aca4b8d15
Revises: 
Create Date: 2026-04-22 20:51:11.458271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc5aca4b8d15'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dictionary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lang', sa.String(length=90), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('words',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=255), nullable=False),
    sa.Column('translate', sa.String(length=255), nullable=False),
    sa.Column('is_studied', sa.Boolean(), nullable=False),
    sa.Column('dictionary_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dictionary_id'], ['dictionary.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    


def downgrade() -> None:
    """Downgrade schema."""
    
    op.drop_table('words')
    op.drop_table('dictionary')
    
